### ISSUE TITLE
Error on Setup

### ISSUE THREAD

**Issue by samucamg** [Eleven-am/frames#1]
I try to setup it on windows, Centos 7, and ubuntu, and aways I got this error.

Error: Unknown column 'datetime_precision' in 'field list'
   0: migration_core::api::SchemaPush
             at migration-engine/core/src/api.rs:161

I'm using mysql from freemysqlhosting.net

**Comment by Eleven-am** [comment]
Hey I believe you have this error because you, freemysqlhosting.net, are using a version of mysql that's inferior to 5.7, Try another mysql provider.

I would also like to say that I am working on a new version of frames that works with a standard db that is easier to set up if you'd like I can inform you when this newer version is available

**Comment by Eleven-am** [comment]
I have made an update to the application. you no longer need mysql to work. you can just use the free supabase SAAS. contact me for me info. Thanks for checking out the application

**Comment by samucamg** [comment]
Sounds goog.   I will try it today.
Thanks



Em seg., 9 de mai. de 2022 às 07:19, Roy Ossai ***@***.***>
escreveu:
